### ISSUE TITLE
[PE-D][Tester C] Inconsistent documentation - help

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T13-1/tp#52]
In UG, suggested help command is 'help exit'

but using that as an input does not work

=========================
help exit
=========================

![Screenshot 2024-04-05 at 3.56.23 PM.png](https://raw.githubusercontent.com/dylansiew/ped/main/files/d849a988-e617-4efb-ac40-b4bf99fb7ac8.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: dylansiew/ped#3

**Comment by Geinzit** [comment]
Thank you! The appropriate instructions for this command has now been added.
