### ISSUE TITLE
[PE-D][Tester A] generate: able to input nothing when answering

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T13-1/tp#60]
![image.png](https://raw.githubusercontent.com/HengShuHong/ped/main/files/72d0a6b7-bf38-4256-9021-b6ab3d6f5dc9.png)

In this screenshot, I am able to not have any input. While there is an error message that states invalid input, it would be great if I could be prompted again for a valid input as I may have accidentally clicked the enter button by accident

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: HengShuHong/ped#2

**Comment by Geinzit** [comment]
Closed. Same as https://github.com/AY2324S2-CS2113-T13-1/tp/issues/54
