### ISSUE TITLE
[PE-D][Tester A] generate: program crashes when there is a negative NUMBER_OF_PROBLEMS

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-T13-1/tp#65]
![image.png](https://raw.githubusercontent.com/HengShuHong/ped/main/files/8cb2a26b-7ba6-4dee-af91-c32d9349e8ac.png)

In the screenshot, when i input NUMBER_OF_PROBLEMS as -4, the program crashes. Perhaps there could be an exception handling that ensures that the NUMBER_OF_PROBLEMS cannot be negative

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: HengShuHong/ped#6

**Comment by Geinzit** [comment]
Closed. Same as https://github.com/AY2324S2-CS2113-T13-1/tp/issues/50
