### ISSUE TITLE
[PE-D][Tester A] UG: error message shows despite following user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T13-1/tp#69]
![image.png](https://raw.githubusercontent.com/HengShuHong/ped/main/files/7bcee0ae-0265-4e35-b6e5-8ded5c1880bc.png)

There is an error message that shows up even though i enter the exact same inputs from the user guide

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: HengShuHong/ped#9

**Comment by Geinzit** [comment]
Closed. Same as https://github.com/AY2324S2-CS2113-T13-1/tp/issues/70
