### ISSUE TITLE
[PE-D][Tester B] Unable to Handle Invalid answer 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T13-1/tp#73]
When user answering the question and input an invalid command like a sign, it will shows invalid input and please enter a number. But it won't go back to the question and give user another change to answer.

You could set a loop until it get a valid answer.

![截屏2024-04-05 下午5.28.07.png](https://raw.githubusercontent.com/a-wild-chocolate/ped/main/files/3eb506c9-1593-48a4-af77-e455c970de59.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: a-wild-chocolate/ped#6

**Comment by Geinzit** [comment]
Closed. Same as https://github.com/AY2324S2-CS2113-T13-1/tp/issues/54
